# Generated by Django 4.1.7 on 2023-03-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldjia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decades',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='decades',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
