# Generated by Django 4.1.7 on 2023-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_year", models.CharField(max_length=100)),
                ("end_year", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Fads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.TextField()),
                ("description", models.CharField(max_length=200)),
                ("decade", models.CharField(max_length=100)),
            ],
        ),
    ]
