# Generated by Django 4.1.7 on 2023-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_fad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fad',
            name='description',
            field=models.CharField(default='no descritption name', max_length=100),
        ),
        migrations.AddField(
            model_name='fad',
            name='image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fad',
            name='name',
            field=models.CharField(default='no decade name', max_length=100),
        ),
    ]
