# Generated by Django 4.2.3 on 2023-07-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decade', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('image_url', models.CharField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fad', to='nostaldja.decade')),
            ],
        ),
        migrations.DeleteModel(
            name='Fads',
        ),
    ]
