# Generated by Django 4.2.3 on 2023-07-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0002_fad_delete_fads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fad',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fad', to='nostaldja.decade'),
        ),
        migrations.AlterField(
            model_name='fad',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
